services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/code

  worker:
    build: .
    command: celery -A app.core.celery_app worker --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/code
