[project]
name = "buildgem-final-project"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.20.0",
    "bcrypt==4.0.1",
    "celery>=5.6.3",
    "fastapi>=0.141.1",
    "passlib>=1.7.4",
    "psycopg>=3.3.6",
    "psycopg2-binary>=2.9.13",
    "pydantic-settings>=2.15.0",
    "pydantic[email]>=2.13.4",
    "python-jose>=3.5.0",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.54.0",
]
[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
