"""remove is_authorized from telegram_groups, default is_active false

Revision ID: 5ac96808a3f2
Revises: 
Create Date: 2026-09-03 03:29:59.533489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5ac96808a3f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_groups', 'is_authorized')
    op.alter_column('telegram_groups', 'is_active', server_default=sa.false(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_groups', sa.Column('is_authorized', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('telegram_groups', 'is_active', server_default=sa.true(), nullable=True)
    # ### end Alembic commands ###
