"""simplified notification_preferences to group-only subscriptions

Revision ID: beba93632082
Revises: 77677d3e7dcb
Create Date: 2026-09-26 18:40:16.176871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beba93632082'
down_revision: Union[str, Sequence[str], None] = '77677d3e7dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification_preferences', 'group_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint('unique_user_group_subscription', 'notification_preferences', ['user_id', 'group_id'])
    op.drop_constraint(op.f('notification_preferences_keyword_id_fkey'), 'notification_preferences', type_='foreignkey')
    op.drop_constraint('check_at_least_one_not_null', 'notification_preferences', type_='check')
    op.drop_column('notification_preferences', 'category')
    op.drop_column('notification_preferences', 'keyword_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_preferences', sa.Column('keyword_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('notification_preferences', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('notification_preferences_keyword_id_fkey'), 'notification_preferences', 'keywords',
                          ['keyword_id'], ['id'])
    op.create_check_constraint(
        'check_at_least_one_not_null',
        'notification_preferences',
        "NOT (group_id IS NULL AND keyword_id IS NULL AND category IS NULL)"
    )
    op.drop_constraint('unique_user_group_subscription', 'notification_preferences', type_='unique')
    op.alter_column('notification_preferences', 'group_id',
                    existing_type=sa.UUID(),
                    nullable=True)    # ### end Alembic commands ###
